name: Deploy Laravel Application

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no username@yourserver.com << 'EOF'
            cd /path/to/your/laravel/project
            git pull origin main
            composer install --no-interaction
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
          EOF
