name: Laravel CI

on:
  push:
    branches:
      - master # Change to your default branch
  pull_request:
    branches:
      - master # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust PHP version if necessary
          extensions: mbstring, xml, bcmath, curl, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

- name: Deploy to Production
  if: github.ref == 'refs/heads/master'
  env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
    PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
    APP_PATH: ${{ secrets.APP_PATH }}
  run: |
    set -x
    mkdir -p ~/.ssh # Ensure .ssh directory exists
    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa # Write private key to file
    chmod 600 ~/.ssh/id_rsa # Set permissions
    ssh-keyscan -H "${PRODUCTION_HOST}" >> ~/.ssh/known_hosts # Add host to known_hosts
    ssh ${PRODUCTION_USER}@${PRODUCTION_HOST} << 'EOF'
      cd ${APP_PATH}
      git pull origin master
      composer install --prefer-dist --no-progress --no-suggest
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
    EOF
