name: Laravel CI

on:
  push:
    branches:
      - master   # Change this to your default branch
  pull_request:
    branches:
      - master   # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Change to your desired PHP version
          extensions: mbstring, xml, bcmath, curl, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here
          # For example, you could use SSH to deploy your application
          # ssh user@your-server 'cd /path/to/your/app && git pull && php artisan migrate'
