name: Laravel CI

on: 
  push:
    branches:
      - master   # Change this to your default branch
  pull_request:
    branches:
      - master   # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Change to your desired PHP version
          extensions: mbstring, xml, bcmath, curl, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate 

      - name: Run database migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
          PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          echo "Setting up SSH agent..."
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${PRODUCTION_HOST}" >> ~/.ssh/known_hosts

          echo "Deploying to production server..."
          ssh ${PRODUCTION_USER}@${PRODUCTION_HOST} << 'EOF'
            cd ${APP_PATH}
            git pull origin master
            composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
          EOF
