name: Deploy Laravel Project

on:
  push:
    branches:
      - master  # or the branch you want to trigger deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@3.88.98.228 "cd /path/to/your/project && git pull && composer install && php artisan migrate"
