name: Laravel CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP 8.3
      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, zip
          coverage: xdebug

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      # Create .env.testing file
      - name: Set up .env.testing
        run: |
          cp .env .env.testing
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env.testing
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=:memory:" >> .env.testing

      # Run database migrations (optional, if needed)
      - name: Run migrations
        run: |
          php artisan migrate --env=testing --force

      # Run tests
      - name: Run tests
        run: |
          php artisan test --env=testing

  deploy:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      # Checkout code again for deployment
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH keys for deployment (assuming you've set up your SSH keys securely)
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      # Deploy to server
      - name: Deploy to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth_sock
        run: |
          eval "$(ssh-agent -s)"
          ssh-add private_key
          ssh -o StrictHostKeyChecking=no root@23.88.98.228 'cd /var/www/laravel-project && git pull origin main && composer install --no-dev --prefer-dist && php artisan migrate --force'
