name: Deploy Laravel Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, xml, zip, pdo, pdo_mysql

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh root@23.88.98.228 "cd /var/www/laravel-project && git pull origin main && php artisan migrate --force && php artisan config:cache"
        env:
          SSH_AUTH_SOCK: ${{ steps.ssh-agent.outputs.ssh-auth-sock }}
