needs: build-and-test

if: github.ref == 'refs/heads/master' && success()

runs-on: ubuntu-latest

steps:

  - name: Set up SSH Key for Deployment

    run: |

      mkdir -p ~/.ssh

      echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      chmod 600 ~/.ssh/id_rsa

      ssh-keyscan -H "${{ secrets.PRODUCTION_HOST }}" >> ~/.ssh/known_hosts

  - name: Deploy to Production Server

    env:

      PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}

      PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}

      APP_PATH: ${{ secrets.APP_PATH }}

    run: |

      ssh -o StrictHostKeyChecking=no ${PRODUCTION_USER}@${PRODUCTION_HOST} << EOF

        cd ${APP_PATH}

        git fetch --all

        git reset --hard origin/master

        composer install --prefer-dist --no-progress --no-suggest

        php artisan migrate --force

        php artisan config:cache

        php artisan route:cache

      EOF
