name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up PHP 8.3
    - name: Set up PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath, intl, zip
        coverage: xdebug

    # Install Composer dependencies
    - name: Install Composer dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest

    # Run tests
    - name: Run tests
      run: |
        php artisan test

  deploy:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    # Checkout code again for deployment
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up SSH keys for deployment (assuming you've set up your SSH keys securely)
    - name: Set up SSH keys
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

    # Deploy to server
    - name: Deploy to server
      run: |
        ssh -i private_key root@23.88.98.228 'cd /var/www/laravel-project && git pull origin main && composer install && php artisan migrate'
